### ISSUE TITLE
ncnnRay++ broken link

### ISSUE THREAD

**Issue by gqgs** [zchrissirhcz/awesome-ncnn#15]
https://github.com/zchrissirhcz/awesome-ncnn/blame/master/README.md#L134

https://github.com/QuantScientist/ncnnRay 404s

**Comment by zchrissirhcz** [comment]
It seems the original author of ncnnRay just deleted this repo, together with its github account.
You may search in github "ncnnRay", find the forked ones.

**Comment by zchrissirhcz** [comment]
> It seems more useful to remove it or update it to link to one of the aforementioned forks.

Thanks for mentioning this. Now the readme is updated.
