### ISSUE TITLE
ncnn in Swift

### ISSUE THREAD

**Issue by zhuzilin** [zchrissirhcz/awesome-ncnn#5]
https://github.com/zhuzilin/ncnn-swift

This is a project of using ncnn in Swift for modern iOS development. Right now it has an image classification exampe and I may add an object detection one in the future. It will help Swift iOS developers utilize ncnn~

**Comment by zchrissirhcz** [comment]
Thanks! Now added to readme.md

**Comment by zhuzilin** [comment]
@zchrissirhcz I've added the object detection example~

**Comment by zchrissirhcz** [comment]
@zhuzilin Cool! Now I updated again.

**Comment by zchrissirhcz** [comment]
Close due to not active talked. Feel free to re-open if updated.
