### ISSUE TITLE
Is there a demo app of image classification with ncnn ?

### ISSUE THREAD

**Issue by wwdok** [zchrissirhcz/awesome-ncnn#7]

**Comment by zchrissirhcz** [comment]
For image classification with ncnn, may refer to the following:

https://github.com/Tencent/ncnn/blob/master/examples/squeezenet.cpp

https://github.com/nihui/ncnn-android-squeezenet

**Comment by zchrissirhcz** [comment]
This repo currently lacks some basic examples, but people can find them in official ncnn github page:

https://github.com/Tencent/ncnn#example-project

**Comment by wwdok** [comment]
Thanks for your information !
